# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

---
- tags:
    - database
    - database/client
  block:
    - name: Install RPM packages for database clients
      package:
        name:
          - postgresql
          - libpq-devel
        state: present
      tags:
        - packages
